# Generated by Django 5.2 on 2025-05-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="test",
            new_name="text",
        ),
    ]
